title = "Trap receiver configeration"

# Доступные типы контроллеров:
# Поток (S) -> Поток, протокол stcip
# Поток (P) -> Поток, протокол ug-405
# Swarco    -> Swarco, протокол stcip
# Peek      -> Peek, протокол ug-405


# Список списков интерфейсов для получения trap.
# Каждый вложенный список - один зарегистрированный интерфейс,
# где индекс 0 -> ip(строка), индекс 1 -> порт(целое число)
network_interfaces = [ ["192.168.45.248", 1162] ]

# Обработчики
[handlers]
all_incoming_notifications = true
# Обработчики "cycles" - список вложенных списков,
# где у вложенного списка:
# index[0] = ip-addr (строка)
# index[1] = тип контроллера (строка)
# index[2] = стартовая фаза смены цикла (целое число)
cycles = [ ["10.45.154.11", "Поток (S)", 1, { 1 = 2 }] ]



